# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - nightly
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  exclude:
    - os: windows
      julia: 1.2
    - os: windows
      julia: 1.3
  include:
    - os: windows
      arch: i386
      julia: 1.0
    - os: windows
      arch: i386
      julia: 1.1
    - os: windows
      arch: i386
      julia: nightly
    - stage: Documentation
      julia: 1.1
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
